/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package survivalist.frames;

import java.awt.event.KeyEvent;

/**
 *
 * @author Jerry
 */
public class InventoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form InventoryFrame
     */
    public InventoryFrame() {
        initComponents();

        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jlInventorygMenuBanner = new javax.swing.JLabel();
        jlItem1 = new javax.swing.JLabel();
        jlItem2 = new javax.swing.JLabel();
        jlItem3 = new javax.swing.JLabel();
        jlItem4 = new javax.swing.JLabel();
        jlItem5 = new javax.swing.JLabel();
        jlItem6 = new javax.swing.JLabel();
        jlItem7 = new javax.swing.JLabel();
        jlItem8 = new javax.swing.JLabel();
        jlItem9 = new javax.swing.JLabel();
        jbExit = new javax.swing.JButton();
        jbHowToPlay = new javax.swing.JButton();
        jlInventoryBackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(748, 458));
        setMinimumSize(new java.awt.Dimension(748, 458));

        jLayeredPane1.setMaximumSize(new java.awt.Dimension(748, 458));
        jLayeredPane1.setMinimumSize(new java.awt.Dimension(748, 458));

        jlInventorygMenuBanner.setFont(new java.awt.Font("Showcard Gothic", 0, 36)); // NOI18N
        jlInventorygMenuBanner.setForeground(new java.awt.Color(93, 184, 93));
        jlInventorygMenuBanner.setText("Inventory");
        jlInventorygMenuBanner.setToolTipText("");
        jLayeredPane1.add(jlInventorygMenuBanner);
        jlInventorygMenuBanner.setBounds(280, 0, 210, 50);

        jlItem1.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem1.setForeground(new java.awt.Color(110, 162, 239));
        jlItem1.setText("Item 1 and quantity");
        jLayeredPane1.add(jlItem1);
        jlItem1.setBounds(60, 70, 210, 30);

        jlItem2.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem2.setForeground(new java.awt.Color(110, 162, 239));
        jlItem2.setText("Item 2 and quantity");
        jLayeredPane1.add(jlItem2);
        jlItem2.setBounds(60, 110, 210, 30);

        jlItem3.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem3.setForeground(new java.awt.Color(110, 162, 239));
        jlItem3.setText("Item 3 and quantity");
        jLayeredPane1.add(jlItem3);
        jlItem3.setBounds(60, 150, 210, 30);

        jlItem4.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem4.setForeground(new java.awt.Color(110, 162, 239));
        jlItem4.setText("Item 4 and quantity");
        jLayeredPane1.add(jlItem4);
        jlItem4.setBounds(60, 190, 210, 30);

        jlItem5.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem5.setForeground(new java.awt.Color(110, 162, 239));
        jlItem5.setText("Item 5 and quantity");
        jLayeredPane1.add(jlItem5);
        jlItem5.setBounds(60, 230, 210, 30);

        jlItem6.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem6.setForeground(new java.awt.Color(110, 162, 239));
        jlItem6.setText("Item 6 and quantity");
        jLayeredPane1.add(jlItem6);
        jlItem6.setBounds(60, 270, 210, 30);

        jlItem7.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem7.setForeground(new java.awt.Color(110, 162, 239));
        jlItem7.setText("Item 7 and quantity");
        jLayeredPane1.add(jlItem7);
        jlItem7.setBounds(60, 310, 210, 30);

        jlItem8.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem8.setForeground(new java.awt.Color(110, 162, 239));
        jlItem8.setText("Item 8 and quantity");
        jLayeredPane1.add(jlItem8);
        jlItem8.setBounds(60, 350, 210, 30);

        jlItem9.setFont(new java.awt.Font("Showcard Gothic", 0, 18)); // NOI18N
        jlItem9.setForeground(new java.awt.Color(110, 162, 239));
        jlItem9.setText("Item 9 and quantity");
        jLayeredPane1.add(jlItem9);
        jlItem9.setBounds(60, 390, 210, 30);

        jbExit.setBackground(new java.awt.Color(43, 72, 130));
        jbExit.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jbExit.setForeground(new java.awt.Color(132, 193, 255));
        jbExit.setText("<html><a style='text-decoration:underline'>E</a>xit</html>");
        jbExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbExit.setFocusPainted(false);
        jbExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExitActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jbExit);
        jbExit.setBounds(580, 420, 160, 30);

        jbHowToPlay.setBackground(new java.awt.Color(43, 72, 130));
        jbHowToPlay.setFont(new java.awt.Font("Showcard Gothic", 0, 12)); // NOI18N
        jbHowToPlay.setForeground(new java.awt.Color(132, 193, 255));
        jbHowToPlay.setText("<html><a style='text-decoration:underline'>H</a>ow to Play</html>");
        jbHowToPlay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbHowToPlay.setFocusPainted(false);
        jbHowToPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHowToPlayActionPerformed(evt);
            }
        });
        jbHowToPlay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbHowToPlayKeyPressed(evt);
            }
        });
        jLayeredPane1.add(jbHowToPlay);
        jbHowToPlay.setBounds(580, 380, 160, 30);

        jlInventoryBackgroundImage.setForeground(new java.awt.Color(132, 193, 255));
        jlInventoryBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/survivalist/images/inventoryBackgroundImage.jpg"))); // NOI18N
        jLayeredPane1.add(jlInventoryBackgroundImage);
        jlInventoryBackgroundImage.setBounds(0, 0, 750, 458);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 748, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExitActionPerformed

        GameMenuFrame gameMenuFrame = new GameMenuFrame();
        gameMenuFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jbExitActionPerformed

    private void jbHowToPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHowToPlayActionPerformed

        HowToPlayFrame howToPlayFrame = new HowToPlayFrame();
        howToPlayFrame.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jbHowToPlayActionPerformed

    private void jbHowToPlayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbHowToPlayKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_H) {
            jbHowToPlayActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_E) {
            jbExitActionPerformed(null);
        }
    }//GEN-LAST:event_jbHowToPlayKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jbExit;
    private javax.swing.JButton jbHowToPlay;
    private javax.swing.JLabel jlInventoryBackgroundImage;
    private javax.swing.JLabel jlInventorygMenuBanner;
    private javax.swing.JLabel jlItem1;
    private javax.swing.JLabel jlItem2;
    private javax.swing.JLabel jlItem3;
    private javax.swing.JLabel jlItem4;
    private javax.swing.JLabel jlItem5;
    private javax.swing.JLabel jlItem6;
    private javax.swing.JLabel jlItem7;
    private javax.swing.JLabel jlItem8;
    private javax.swing.JLabel jlItem9;
    // End of variables declaration//GEN-END:variables
}
